server:
  port: 8081

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
    url: jdbc:mysql://localhost:3306/labesimecu
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: luisansiola@gmail.com
    password: eshvwcsmylbypswi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true