server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
    url: jdbc:mysql://localhost:3306/labesimecu
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: luisansiola@gmail.com
    password: P@ssw0rd31!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true